import type { Metadata } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-source-serif",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: {
    default: "App Name",
    template: "%s | App Name",
  },
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "App Name",
  },
};

import { Toaster } from "sonner";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-serif antialiased`}>
          {children}
        <Toaster
          closeButton
          toastOptions={{
            classNames: {
              error: "bg-red-500/80! text-white! border-red-600!",
              success: "bg-green-500! text-white! border-green-600!",
            },
          }}
        />
      </body>
    </html>
  );
}
